
build-ll:
	g++ linked-list.cpp -o ./build/linked-list

run-ll:
	g++ linked-list.cpp -o ./build/linked-list && ./build/linked-list

build-q:
	g++ queues.cpp -o ./build/queues

run-q:
	g++ queues.cpp -o ./build/queues && ./build/queues

build-stack:
	g++ stack.cpp -o ./build/stack

run-stack:
	g++ stack.cpp -o ./build/stack && ./build/stack
